# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sdc/red_pitaya.xdc

# IP: ip/bram_20x49k_80x12k/bram_20x49k_80x12k.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_20x49k_80x12k || ORIG_REF_NAME==bram_20x49k_80x12k} -quiet] -quiet

# IP: ip/bram_18x4k_36x2k/bram_18x4k_36x2k.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_18x4k_36x2k || ORIG_REF_NAME==bram_18x4k_36x2k} -quiet] -quiet

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_protocol_converter_0_0 || ORIG_REF_NAME==system_axi_protocol_converter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0 || ORIG_REF_NAME==system_proc_sys_reset_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0/system_processing_system7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0 || ORIG_REF_NAME==system_processing_system7_0} -quiet] -quiet

# IP: bd/system/ip/system_xadc_0/system_xadc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xadc_0 || ORIG_REF_NAME==system_xadc_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0/system_xlconstant_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0 || ORIG_REF_NAME==system_xlconstant_0} -quiet] -quiet

# XDC: ip/bram_20x49k_80x12k/bram_20x49k_80x12k_ooc.xdc

# XDC: ip/bram_18x4k_36x2k/bram_18x4k_36x2k_ooc.xdc

# XDC: bd/system/system_ooc.xdc
