# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/user_35t/user_35t.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t || ORIG_REF_NAME==user_35t} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_emc_0_0/user_35t_axi_emc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_axi_emc_0_0 || ORIG_REF_NAME==user_35t_axi_emc_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_gpio_0_0/user_35t_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_axi_gpio_0_0 || ORIG_REF_NAME==user_35t_axi_gpio_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_gpio_1_0/user_35t_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_axi_gpio_1_0 || ORIG_REF_NAME==user_35t_axi_gpio_1_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_intc_0_0/user_35t_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_axi_intc_0_0 || ORIG_REF_NAME==user_35t_axi_intc_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xbar_0/user_35t_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_xbar_0 || ORIG_REF_NAME==user_35t_xbar_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_s00_regslice_0/user_35t_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_s00_regslice_0 || ORIG_REF_NAME==user_35t_s00_regslice_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_s00_data_fifo_0/user_35t_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_s00_data_fifo_0 || ORIG_REF_NAME==user_35t_s00_data_fifo_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_s01_regslice_0/user_35t_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_s01_regslice_0 || ORIG_REF_NAME==user_35t_s01_regslice_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_s01_data_fifo_0/user_35t_s01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_s01_data_fifo_0 || ORIG_REF_NAME==user_35t_s01_data_fifo_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_m00_data_fifo_0/user_35t_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_m00_data_fifo_0 || ORIG_REF_NAME==user_35t_m00_data_fifo_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_m00_regslice_0/user_35t_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_m00_regslice_0 || ORIG_REF_NAME==user_35t_m00_regslice_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_mem_intercon_0/user_35t_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_axi_mem_intercon_0 || ORIG_REF_NAME==user_35t_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_timer_0_0/user_35t_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_axi_timer_0_0 || ORIG_REF_NAME==user_35t_axi_timer_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_uartlite_0_0/user_35t_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_axi_uartlite_0_0 || ORIG_REF_NAME==user_35t_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_clk_wiz_0_0/user_35t_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_clk_wiz_0_0 || ORIG_REF_NAME==user_35t_clk_wiz_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_mdm_1_0/user_35t_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_mdm_1_0 || ORIG_REF_NAME==user_35t_mdm_1_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_microblaze_0_0/user_35t_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_microblaze_0_0 || ORIG_REF_NAME==user_35t_microblaze_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xbar_1/user_35t_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_xbar_1 || ORIG_REF_NAME==user_35t_xbar_1} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_microblaze_0_axi_periph_0/user_35t_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_microblaze_0_axi_periph_0 || ORIG_REF_NAME==user_35t_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_dlmb_bram_if_cntlr_0/user_35t_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==user_35t_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_dlmb_v10_0/user_35t_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_dlmb_v10_0 || ORIG_REF_NAME==user_35t_dlmb_v10_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_ilmb_bram_if_cntlr_0/user_35t_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==user_35t_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_ilmb_v10_0/user_35t_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_ilmb_v10_0 || ORIG_REF_NAME==user_35t_ilmb_v10_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_lmb_bram_0/user_35t_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_lmb_bram_0 || ORIG_REF_NAME==user_35t_lmb_bram_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_rst_clk_wiz_0_100M_0/user_35t_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==user_35t_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xlconcat_0_0/user_35t_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_35t_xlconcat_0_0 || ORIG_REF_NAME==user_35t_xlconcat_0_0} -quiet] -quiet

# XDC: bd/user_35t/user_35t_ooc.xdc
