# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/sf_XilinxUbuntuVMShare/RP_SeqPID/rp_seqpid_src/seqpid/fpga_project/redpitaya.srcs/sources_1/ip/red_pitaya_pll_mod/red_pitaya_pll_mod.xci
# IP: The module: 'red_pitaya_pll_mod' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_XilinxUbuntuVMShare/RP_SeqPID/rp_seqpid_src/seqpid/fpga_project/redpitaya.srcs/sources_1/ip/red_pitaya_pll_mod/red_pitaya_pll_mod_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_pll_mod'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/sf_XilinxUbuntuVMShare/RP_SeqPID/rp_seqpid_src/seqpid/fpga_project/redpitaya.srcs/sources_1/ip/red_pitaya_pll_mod/red_pitaya_pll_mod.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_pll_mod'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/sf_XilinxUbuntuVMShare/RP_SeqPID/rp_seqpid_src/seqpid/fpga_project/redpitaya.srcs/sources_1/ip/red_pitaya_pll_mod/red_pitaya_pll_mod_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_pll_mod'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/sf_XilinxUbuntuVMShare/RP_SeqPID/rp_seqpid_src/seqpid/fpga_project/redpitaya.srcs/sources_1/ip/red_pitaya_pll_mod/red_pitaya_pll_mod.xci
# IP: The module: 'red_pitaya_pll_mod' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_XilinxUbuntuVMShare/RP_SeqPID/rp_seqpid_src/seqpid/fpga_project/redpitaya.srcs/sources_1/ip/red_pitaya_pll_mod/red_pitaya_pll_mod_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_pll_mod'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/sf_XilinxUbuntuVMShare/RP_SeqPID/rp_seqpid_src/seqpid/fpga_project/redpitaya.srcs/sources_1/ip/red_pitaya_pll_mod/red_pitaya_pll_mod.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_pll_mod'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/sf_XilinxUbuntuVMShare/RP_SeqPID/rp_seqpid_src/seqpid/fpga_project/redpitaya.srcs/sources_1/ip/red_pitaya_pll_mod/red_pitaya_pll_mod_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_pll_mod'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
