# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.cache/wt [current_project]
set_property parent.project_path /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/sources_1/bd/system/hdl/system_wrapper.v
  /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/sources_1/axi_slave.v
  /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/sources_1/red_pitaya_ps.v
  /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/sources_1/red_pitaya_hk.v
  /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/sources_1/red_pitaya_analog.v
  /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/sources_1/red_pitaya_daisy.v
  /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/sources_1/red_pitaya_top.v
}
add_files /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/sources_1/bd/system/system.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/constrs_1/red_pitaya.xdc
set_property used_in_implementation false [get_files /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/constrs_1/red_pitaya.xdc]

read_xdc /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/constrs_1/red_pitaya_top.xdc
set_property used_in_implementation false [get_files /home/nico/Physique/RedPitaya/blink_example/red_pitaya/red_pitaya.srcs/constrs_1/red_pitaya_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top red_pitaya_top -part xc7z010clg400-1 -flatten_hierarchy none -bufg 16 -keep_equivalent_registers


write_checkpoint -force -noxdef red_pitaya_top.dcp

catch { report_utilization -file red_pitaya_top_utilization_synth.rpt -pb red_pitaya_top_utilization_synth.pb }
