# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ciprian/Documents/Github/Cmod-A7/hw/proj/hw.srcs/sources_1/bd/user_35t/ip/user_35t_clk_wiz_0_0/user_35t_clk_wiz_0_0.xci
# IP: The module: 'user_35t_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ciprian/Documents/Github/Cmod-A7/hw/proj/hw.srcs/sources_1/bd/user_35t/ip/user_35t_clk_wiz_0_0/user_35t_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ciprian/Documents/Github/Cmod-A7/hw/proj/hw.srcs/sources_1/bd/user_35t/ip/user_35t_clk_wiz_0_0/user_35t_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ciprian/Documents/Github/Cmod-A7/hw/proj/hw.srcs/sources_1/bd/user_35t/ip/user_35t_clk_wiz_0_0/user_35t_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ciprian/Documents/Github/Cmod-A7/hw/proj/hw.srcs/sources_1/bd/user_35t/ip/user_35t_clk_wiz_0_0/user_35t_clk_wiz_0_0.xci
# IP: The module: 'user_35t_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ciprian/Documents/Github/Cmod-A7/hw/proj/hw.srcs/sources_1/bd/user_35t/ip/user_35t_clk_wiz_0_0/user_35t_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ciprian/Documents/Github/Cmod-A7/hw/proj/hw.srcs/sources_1/bd/user_35t/ip/user_35t_clk_wiz_0_0/user_35t_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ciprian/Documents/Github/Cmod-A7/hw/proj/hw.srcs/sources_1/bd/user_35t/ip/user_35t_clk_wiz_0_0/user_35t_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
